services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: blog
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: blog_web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
  # substituir mysql por postgres
    image: postgres:13
    container_name: blog_db
    hostname: db
    environment:
      POSTGRES_DB: neondb
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: npg_n3XJFAouw4xd
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      laravel:
        aliases:
          - db

volumes:
  dbdata:
    driver: local

networks:
  laravel:
    driver: bridge