services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: blog
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: blog_web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: blog_db
    hostname: db
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      laravel:
        aliases:
          - db

volumes:
  dbdata:
    driver: local

networks:
  laravel:
    driver: bridge